"""empty message

Revision ID: 0090a9357f3f
Revises: 81d5f3219e8b
Create Date: 2022-03-15 11:35:00.952171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0090a9357f3f'
down_revision = '81d5f3219e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_ibfk_1', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_ibfk_1', 'product', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
