"""empty message

Revision ID: 0f7d6696033a
Revises: 9a113095bbf7
Create Date: 2022-03-14 12:58:49.814650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f7d6696033a'
down_revision = '9a113095bbf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('prod_stock', sa.Boolean(),server_default='f', nullable=True))
    op.drop_column('product', 'stock')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('stock', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('product', 'prod_stock')
    # ### end Alembic commands ###
