"""empty message

Revision ID: 1a37c5475686
Revises: fb276970baa6
Create Date: 2022-03-15 12:25:51.817070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a37c5475686'
down_revision = 'fb276970baa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('prod_stock', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'prod_stock')
    # ### end Alembic commands ###
