"""empty message

Revision ID: 1a7e9ab05169
Revises: 1246959a680b
Create Date: 2022-03-23 10:33:17.036045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7e9ab05169'
down_revision = '1246959a680b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('prod_stock', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'prod_stock')
    # ### end Alembic commands ###
