"""empty message

Revision ID: 81d5f3219e8b
Revises: f65a1b47f679
Create Date: 2022-03-15 11:05:29.801897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d5f3219e8b'
down_revision = 'f65a1b47f679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('prod_stock', sa.Boolean(), nullable=True, create_constraint=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'prod_stock')
    # ### end Alembic commands ###
