"""empty message

Revision ID: 907403b2e2aa
Revises: 96e80063a7f5
Create Date: 2022-03-14 17:44:46.306930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907403b2e2aa'
down_revision = '96e80063a7f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('prod_name', table_name='product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('prod_name', 'product', ['prod_name'], unique=False)
    # ### end Alembic commands ###
