"""empty message

Revision ID: 96e80063a7f5
Revises: 0f7d6696033a
Create Date: 2022-03-14 14:29:54.537725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96e80063a7f5'
down_revision = '0f7d6696033a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('prod_name', table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('prod_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('prod_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('prod_price', mysql.FLOAT(), nullable=False),
    sa.Column('prod_image', sa.BLOB(), nullable=False),
    sa.Column('prod_description', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('product_date', mysql.TEXT(), nullable=True),
    sa.Column('modified_date', sa.DATE(), nullable=True),
    sa.Column('prod_stock', mysql.TINYINT(display_width=1), autoincrement=False,server_default='f',nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='product_ibfk_1'),
    sa.PrimaryKeyConstraint('prod_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('prod_name', 'product', ['prod_name'], unique=False)
    # ### end Alembic commands ###
