"""empty message

Revision ID: 9a113095bbf7
Revises: 1add65dfe508
Create Date: 2022-03-14 10:08:00.232930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a113095bbf7'
down_revision = '1add65dfe508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('modified_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'modified_date')
    # ### end Alembic commands ###
