"""empty message

Revision ID: c14d3d4df386
Revises: 
Create Date: 2022-03-09 13:01:43.015837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c14d3d4df386'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('register_date', sa.DateTime(), nullable=True))
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.drop_column('user', 'register_date')
    # ### end Alembic commands ###
